extends Node

const PANEL_FLOOR = "PANEL_FLOOR"
const DARK_PANEL_FLOOR = "DARK_PANEL_FLOOR"
const STONE_FLOOR = "STONE_FLOOR"
const LIGHT_PANEL_FLOOR = "LIGHT_PANEL_FLOOR"
const LIGHT_FLOOR = "LIGHT_FLOOR"

const DARK_GREEN_WALL = "DARK_GREEN_WALL"
const DARK_RED_PANEL_WALL = "DARK_RED_PANEL_WALL"
const DARK_RED_WALL = "DARK_RED_WALL"
const ORANGE_TILE_WALL = "ORANGE_TILE_WALL"
const LIGHT_GREEN_WALL = "LIGHT_GREEN_WALL"
const ORANGE_PANEL_WALL = "ORANGE_PANEL_WALL"
const CREAM_WALL = "CREAM_WALL"

const CHAIR_OAK_FRONT = "CHAIR_OAK_FRONT"
const CHAIR_OAK_SIDE = "CHAIR_OAK_SIDE"
const CHAIR_WHITE_BACK = "CHAIR_WHITE_BACK"
const CHAIR_WHITE_FRONT = "CHAIR_WHITE_FRONT"
const CHAIR_WHITE_SIDE = "CHAIR_WHITE_SIDE"
const COFFEE_TABLE_ORANGE = "COFFEE_TABLE_ORANGE"
const COFFEE_TABLE_ORANGE_SIDE = "COFFEE_TABLE_ORANGE_SIDE"
const COFFEE_TABLE_PINE = "COFFEE_TABLE_PINE"
const COFFEE_TABLE_PINE_SIDE = "COFFEE_TABLE_PINE_SIDE"
const RUG_BIG =  "RUG_BIG"
const RUG_ROUND = "RUG_ROUND"
const RUG_SMALL = "RUG_SMALL"
const RUG_SMALL_SIDE = "RUG_SMALL_SIDE"
const SMALL_ROUND_CHAIR = "SMALL_ROUND_CHAIR"
const TABLE_ROTUND_ORANGE = "TABLE_ROTUND_ORANGE"


const FLOOR_LAYER = 0
const WALL_LAYER = 1
const FURNITURE_LAYER = 2

