extends Node

const PANEL_FLOOR = "PANEL_FLOOR"
const DARK_PANEL_FLOOR = "DARK_PANEL_FLOOR"
const STONE_FLOOR = "STONE_FLOOR"
const LIGHT_PANEL_FLOOR = "LIGHT_PANEL_FLOOR"
const LIGHT_FLOOR = "LIGHT_FLOOR"

const DARK_GREEN_WALL = "DARK_GREEN_WALL"
const DARK_RED_PANEL_WALL = "DARK_RED_PANEL_WALL"
const DARK_RED_WALL = "DARK_RED_WALL"
const ORANGE_TILE_WALL = "ORANGE_TILE_WALL"
const LIGHT_GREEN_WALL = "LIGHT_GREEN_WALL"
const ORANGE_PANEL_WALL = "ORANGE_PANEL_WALL"
const CREAM_WALL = "CREAM_WALL"

const FLOOR_LAYER = 0
const WALL_LAYER = 1
const FURNITURE_LAYER = 2

